### ISSUE TITLE
Conflict with text-rendering CSS attribute

### ISSUE THREAD

**Issue by subvertallchris** [garysieling/jquery-highlighttextarea#30]
Hi! I ran into two issues that I wanted to let you know about. Not sure if they warrant fixes in the source but I'll leave them here for your consideration.

The first is that the <mark> tag has styling applied by Bootstrap, which is used heavily enough these days that it seems worth keeping in mind. It adds padding of 0.2em, so the fix is to just specify padding of 0 in your <mark> to override it.

``` css
.highlightTextarea mark {
  line-height:inherit;
  color:transparent;
  padding: 0;
}
```

Easy! The other is a conflict with the text-rendering property. In my case, it was applied to the body, so the highlight div got it, but my textarea didn't. The solution was to add this class to the textarea. 

``` css
.highlightTextarea textarea {
  text-rendering: optimizeLegibility;
}
```

Again, not sure if this was your problem, but thought you'd might like to know!

The end! Thanks for your work on this!
